import Navbar from '@/components/Navbar/Navbar';
import type { Metadata } from 'next';


export const metadata: Metadata = {
  title: 'Perfil - Miçangário',
  description: 'Generated by create next app',
};

export default function ProfileLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
      <Navbar/>
    </>
  );
}
