import type { Metadata } from 'next';


export const metadata: Metadata = {
  title: 'Produto - Miçangário',
  description: 'Generated by create next app',
};

export default function ProductDetailsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
    </>
  );
}
