import type { Metadata } from 'next';
import Navbar from '@/components/Navbar/Navbar';


export const metadata: Metadata = {
  title: 'Miçangário',
  description: 'Generated by create next app',
};

export default function FavoritesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
      <Navbar />
    </>
  );
}
